# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810614c0dc4a0a16b62c70b8049fae41d1aa2d3ccd4196a40854e417d522b69d484f70d462d2644f94590610a11c5e66c29946c2f2f14da470417d93b206389c

test:
  secret_key_base: ba789e2df8c65ac319d5a60bf4530dceda80b20871daed71e67d6d825038c407ba226e78c837dc53445a5bd5d7f30e8acb3685e77cac0a8f1c4433c5b74c322e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
